/**
 * Module that makes working with ANSI escapes easier.
 */

#pragma once

#define TERM_ESC "\x1B["
#define TERM_ESC_END "m"
#define TERM_ARG_SEP ";"
#define TERM_RESET TERM_ESC TERM_ESC_END

#define TERM_ARG_BOLD "1"
#define TERM_ARG_RED "31"
#define TERM_ARG_YELLOW "33"
#define TERM_ARG_BLUE "34"

#define TERM_BOLD TERM_ESC TERM_ARG_BOLD TERM_ESC_END
#define TERM_BOLD_RED TERM_ESC TERM_ARG_BOLD TERM_ARG_SEP TERM_ARG_RED TERM_ESC_END
#define TERM_BOLD_YELLOW TERM_ESC TERM_ARG_BOLD TERM_ARG_SEP TERM_ARG_YELLOW TERM_ESC_END
#define TERM_BOLD_BLUE TERM_ESC TERM_ARG_BOLD TERM_ARG_SEP TERM_ARG_BLUE TERM_ESC_END

#define TERM_WRAP(t, ...) t __VA_ARGS__ TERM_RESET
